import { ListingRow } from '../../interfaces/tables/listing-row';
import { InfoCard } from 'src/app/interfaces/info-card';
import { PageTitle } from './../../interfaces/page-title';
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  templateUrl: './listing.component.html',
  styleUrls: ['./listing.component.scss'],
})
export class ListingComponent {
  pageTitle: PageTitle = {
    iconColor: 'var(--secundaria-2)',
    icon: 'inventory_2',
    title: 'Inventário de Reagentes e Materiais',
    searchBox: true,
    adjustButton: false
  };

  infoCards: InfoCard[] = [
    {
      iconColor: '',
      icon: 'format_list_bulleted',
      title: 'Total de Itens',
      data: '-',
    },
    {
      iconColor: '',
      icon: 'calculate',
      title: 'Valor total',
      data: 'R$ -',
    },
    {
      iconColor: '',
      icon: 'data_usage',
      title: 'Mais Utilizado',
      data: '-',
    },
  ];

  tableRow: ListingRow[] = [
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
    {
      cod: '123',
      desc: 'lorem ipsum',
      tags:  ['EM', 'PF', 'EB'],
      estoque: 12,
      un: 'Kg',
      localizacao: '2345A',
      valor_un: 20,
      valor_tot: 12,
      prod_id: 1,
    },
  ];

  constructor(private router: Router) {}

  openHistory() {
    this.router.navigate(['/history'])
  }
}
